<div style="background: #DDE2FF;
            font-family: Bookerly;
            font-size: 14px; 
            font-weight: 500;
            padding: 30px 5px 30px 5px; 
            border: 30px solid #DDE2FF; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>(Custom CSS files are not reliable for controlling Jupyter font style. To establish the same appearance as the original notebook, depend on the browser to control the font, by setting the desired font faces in the browser settings. For example, Chrome 135 or Firefox 134 can do this. In this notebook series, Bookerly font is for markdown and Monaco is for code.)
     
     
     

</font>                 
</div>

<div style="background: #DDE2FF;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 20px 5px 20px 5px; 
            border: 30px solid #DDE2FF; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>**Chapter 15 Matrices**: Matrix functions and operations. <br><br>
     
     
     

</font>                 
</div>

<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 20px 5px 20px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.1 Show that $\textbf{A} \,+\,\textbf{B}\,=\,\textbf{B} \,+\,\textbf{A}\,$ for<br>

\begin{equation}
\textbf{A}\,=\,
  \begin{bmatrix}
    1 & 2 \\ 
    3 & 4 \\
  \end{bmatrix}
  %
  \hspace{2 em}
  \textbf{B}\,=\,
  \begin{bmatrix}
    5 & 6 \\
    7 & 8 \\
  \end{bmatrix}
  \hspace{24 em}
\end{equation}

     
     
     

</font> 
</div>

<div style="background: #E2FFCC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 10px 5px 10px 5px; 
            border: 30px solid #E2FFCC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>Show that $\textbf{A} \,+\,\textbf{B}\,=\,\textbf{B} \,+\,\textbf{A}\,$ for the two matrices in the description.<br>

The Wolfram Alpha entry lines go like:<br>
!|  {{5, 6}, {7, 8}} + {{1, 2}, {3, 4}} |!<br>
and<br>
!|  {{1, 2}, {3, 4}} + {{5, 6}, {7, 8}} |!<br> 

\begin{equation}
\textbf{A}\,+\textbf{B}\,=\,\textbf{B}\,+\textbf{A}\,=\,
  \begin{bmatrix}
    6 & 8 \\ 
    10 & 12 \\
  \end{bmatrix}
  \hspace{24 em}
\end{equation}




</font>                 
</div>

<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 20px 5px 20px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.2 $\:\:$Find $\textbf{A} \,-\,\large\frac{1}{2}\,\small\textbf{B}\,$ for<br>

\begin{equation}
\textbf{A}\,=\,
  \begin{bmatrix}
    1 & 2 \\ 
    3 & 4 \\
  \end{bmatrix}
  %
  \hspace{2 em}
  \textbf{B}\,=\,
  \begin{bmatrix}
    5 & 6 \\
    7 & 8 \\
  \end{bmatrix}
  \hspace{24 em}
\end{equation}


     
     
     

</font> 
</div>

<div style="background: #E2FFCC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 10px 5px 10px 5px; 
            border: 30px solid #E2FFCC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>A subtraction example.

The Wolfram Alpha entry line goes like:<br>
!|  {{1, 2}, {3, 4}} - (1/2) * {{5, 6}, {7, 8}} |!<br>


\begin{equation}
  \begin{bmatrix}
    -\frac{3}{2} & -1 \\ 
    -\frac{1}{2} & 0 \\
  \end{bmatrix}
  \hspace{24 em}
\end{equation}




</font>                 
</div>

<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 20px 5px 20px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.3 $\:\:$Find $\textbf{A}\textbf{B}\,$ and $\textbf{B}\textbf{A}\,$ for<br>

\begin{equation}
\textbf{A}\,=\,
  \begin{bmatrix}
    1 & 2 \\ 
    3 & 4 \\
  \end{bmatrix}
  %
  \hspace{2 em}
  \textbf{B}\,=\,
  \begin{bmatrix}
    5 & 6 \\
    7 & 8 \\
  \end{bmatrix}
  \hspace{24 em}
\end{equation}

     
     
     

</font> 
</div>

<div style="background: #E2FFCC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 10px 5px 10px 5px; 
            border: 30px solid #E2FFCC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>Commutation of multiplication trial.

The Wolfram Alpha entry line goes like:<br>
!|  {{1, 2}, {3, 4}} * {{5, 6}, {7, 8}} |!<br>
and<br>
!|  {{5, 6}, {7, 8}} * {{1, 2}, {3, 4}} |!<br> 


\begin{equation}
  \textbf{A}\,\times\,\textbf{B}\,=\,
  \begin{bmatrix}
    19 & 22 \\ 
    43 & 50 \\
  \end{bmatrix}
  %
  \hspace{3 em}
  \textbf{B}\,\times\,\textbf{A}\,=\,
  \begin{bmatrix}
    23 & 24 \\ 
    31 & 46 \\
  \end{bmatrix}
  \hspace{24 em}
\end{equation}




</font>                 
</div>

<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 20px 5px 20px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.4 $\:\:$Find $\,(2\textbf{A}\,-\,\textbf{B})^2\,$ for<br>

\begin{equation}
\textbf{A}\,=\,
  \begin{bmatrix}
    1 & 2 \\ 
    3 & 4 \\
  \end{bmatrix}
  %
  \hspace{2 em}
  \textbf{B}\,=\,
  \begin{bmatrix}
    5 & 6 \\
    7 & 8 \\
  \end{bmatrix}
  \hspace{24 em}
\end{equation}


     
     
     

</font> 
</div>

<div style="background: #E2FFCC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 10px 5px 10px 5px; 
            border: 30px solid #E2FFCC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>Polynomial squared trial.

For some reason, the Wolfram Alpha entry line needs to be split up into two parts:<br>
!| (2 * {{1, 2}, {3, 4}} - {{5, 6}, {7, 8}} ) |!<br>

to get the intermediate result of {{-3, -2}, {-1, 0}}, then

!| {{-3, -2}, {-1, 0}} ^2 |! to get the final answer, which is shown.


\begin{equation}
  \textbf{A}\,\times\,\textbf{B}\,=\,
  \begin{bmatrix}
    11 & 6 \\ 
    3 & 2 \\
  \end{bmatrix}
  \hspace{24 em}
\end{equation}




</font>                 
</div>

<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 20px 5px 20px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.5 $\:\:$Find $\textbf{A}\textbf{B}\,$ and $\textbf{B}\textbf{A}\,$ for<br>


\begin{equation}
\textbf{A}\,=\,
  \begin{bmatrix}
    1 & 2 & 3 \\ 
    4 & 5 & 6\\
  \end{bmatrix}
  %
  \hspace{2 em}
  \textbf{B}\,=\,
  \begin{bmatrix}
    7 & 0 \\
    8 & -1 \\
  \end{bmatrix}
  \hspace{24 em}
\end{equation}


     
     
     

</font> 
</div>

<div style="background: #E2FFCC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 10px 5px 10px 5px; 
            border: 30px solid #E2FFCC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>The operation of multiplication is not defined for 3-column matrix times a 2-row matrix. However, looking at $\textbf{BA}$, below is the outcome.

The entry into Wolfram Alpha goes like:<br>
 {{7, 0}, {8, -1}} * {{1, 2, 3}, {4, 5, 6}} 

\begin{equation}
  \hspace{2 em}
  \textbf{B}\times\textbf{A}\,=\,
  \begin{bmatrix}
    7 & 14 & 21 \\
    4 & 11 & 18 \\
  \end{bmatrix}
  \hspace{24 em}
\end{equation}
</font>                 
</div>

<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 20px 5px 20px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.6 $\:\:$Find $\textbf{A}\textbf{B}\,$ and $\textbf{A}\textbf{C}\,$ if<br>


\begin{equation}
\textbf{A}\,=\,
  \begin{bmatrix}
    4 & 2 & 0 \\ 
    2 & 1 & 0 \\
    -2 & -1 & 1 \\
  \end{bmatrix},
  %
  \hspace{2 em}
  \textbf{B}\,=\,
  \begin{bmatrix}
    2 & 3 & 1 \\
    2 & -2 & -2 \\
    -1 & 2 & 1 \\
  \end{bmatrix},
  %
  \hspace{2 em}
  \textbf{C}\,=\,
  \begin{bmatrix}
    3 & 1 & -3 \\
    0 & 2 & 6 \\
    -1 & 2 & 1 \\
  \end{bmatrix}
  \hspace{5 em}
\end{equation}


     
     
     

</font> 
</div>

In [48]:
from scipy import linalg
import numpy as np
  
a = np.array([[4, 2, 0], [2, 1, 0], [-2, -1, 1]])
b = np.array([[2, 3, 1], [2, -2, -2], [-1, 2, 1]])
c = np.array([[3, 1, -3], [0, 2, 6], [-1, 2, 1]])
  
#of the 3 ways to multiply arrays in python, 
#"matmul" gives the "matrix product"
#"multipy" returns element-wise multiplication
#"dot" returns dot product


res1 = np.matmul(a, b)
res2 = np.matmul(a, c)


#for line in res:
    #print ('  '.join(map(str, line)))
print(res1)
print()
print(res2)

[[12  8  0]
 [ 6  4  0]
 [-7 -2  1]]

[[12  8  0]
 [ 6  4  0]
 [-7 -2  1]]


<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 20px 5px 20px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.7 $\:\:$Find $\textbf{A}\textbf{x}\,$ if<br>


\begin{equation}
\textbf{A}\,=\,
  \begin{bmatrix}
    1 & 2 & 3 & 4 \\ 
    5 & 6 & 7 & 8 \\
  \end{bmatrix},
  %
  \hspace{2 em}
  \textbf{x}\,=\,
  \begin{bmatrix}
    9 \\
    -1 \\
    -2 \\
    0 \\
  \end{bmatrix}
  \hspace{25 em}
\end{equation}


     
     
     

</font> 
</div>

In [51]:
from scipy import linalg
import numpy as np
  
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
x = np.array([[9], [-1], [-2], [0]])

  
#of the 3 ways to multiply arrays in python, 
#"matmul" gives the "matrix product"
#"multipy" returns element-wise multiplication
#"dot" returns dot product


res1 = np.matmul(a, x)


#for line in res:
    #print ('  '.join(map(str, line)))
print(res1)
print()


[[ 1]
 [25]]



<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 20px 5px 20px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.8 $\:\:$ Find $\large\frac{d\textbf{A}}{dt}\,$ if <br>


\begin{equation}
\textbf{A}\,=\,
  \begin{bmatrix}
    t^2+1 & e^{2t} \\ 
    \textrm{sin}\,t & 45 \\
  \end{bmatrix}
  \hspace{35 em}
\end{equation}


     
     
     

</font> 
</div>

<div style="background: #E2FFCC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 10px 5px 10px 5px; 
            border: 30px solid #E2FFCC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>The derivative of the matrix can be found with Wolfram Alpha. Using the entry

!| d[{{t^2 + 1, e^(2 * t)}, {sin(t), 45}}]/dt |!

the result is returned:<br><br>
\begin{equation}
\textbf{A}\,=\,
  \begin{bmatrix}
    2t & 2e^{2t} \\ 
    \textrm{cos}\,t & 0 \\
  \end{bmatrix}
  \hspace{35 em}
\end{equation}

Also offered are expressions for the eigenvalues and eigenvectors, for which there is no present need.



</font>                 
</div>

<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 20px 5px 20px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.9 $\:\:$ Find $\large\frac{d\textbf{x}}{dt}\,$ if <br>


\begin{equation}
\textbf{x}\,=\,
  \begin{bmatrix}
    x_1(t) \\ 
    x_2(t) \\
    x_3(t) \\
  \end{bmatrix}
  \hspace{35 em}
\end{equation}

     
     
     

</font> 
</div>

<div style="background: #E2FFCC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 10px 5px 10px 5px; 
            border: 30px solid #E2FFCC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>The derivative of the matrix can be found with Wolfram Alpha. Using the entry

!| differentiate {{x1(t)}, {x2(t)}, {x3(t)}} with respect to t |!

the result is returned:<br><br>
\begin{equation}
\textrm{d/dt {{x1(t)}, {x2(t)}, {x3(t)}}}\,=\,
  \begin{bmatrix}
    x1'(t) \\ 
    x2'(t) \\
    x3'(t) \\
  \end{bmatrix}
  \hspace{35 em}
\end{equation}

Here W|A is prone to ignore the underbar or subscript form, but will cooperate if the condensed form shown above is used.

</font>                 
</div>


<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 100px 5px 100px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.10 $\:\:$ Find $\int\textbf{A}\:{dt}\,$ for $\textbf{A}$ as given in Problem 15.8. <br>


     
     
     

</font> 
</div>

<div style="background: #E2FFCC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 10px 5px 10px 5px; 
            border: 30px solid #E2FFCC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>Wolfram Alpha flatly refuses to integrate over the matrix. Luckily it is an easy matter to integrate component-wise by hand. The matrix that emerges is:<br>


\begin{equation}
\int\textbf{A}dt\,=\,
  \begin{bmatrix}
    t^3/3+t+c_1 & (e^{2t})/2+c_2 \\ 
    \textrm{-cos t}+c_3 & 45t+c_4 \\
  \end{bmatrix}
  \hspace{35 em}
\end{equation}

</font>                 
</div>


<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 20px 5px 20px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.11 $\:\:$ Find $\int_0^1\textbf{x}\:{dt}\,$ if

\begin{equation}
\textbf{x}\,=\,
  \begin{bmatrix}
    1 \\ 
    e^t \\
    0 \\
  \end{bmatrix}
  \hspace{28 em}
\end{equation} <br>


     
     
     

</font> 
</div>

<div style="background: #E2FFCC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 10px 5px 10px 5px; 
            border: 30px solid #E2FFCC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>Again W|A refuses to do the integration. But again it is an easy process and results in:<br>

\begin{equation}
\int\textbf{x}dt\,=\,
  \begin{bmatrix}
    t + c_1 \\ 
    e^t + c_2\\
    c_3 \\
  \end{bmatrix}
  \hspace{35 em}
\end{equation}

The above needs to be evaluated at the upper bound of 1 and at the lower bound of 0, with the answer being the difference between the two. That turns out to be:<br>

\begin{equation}
\textbf{evaluated}\,=\,
  \begin{bmatrix}
    1 \\ 
    e - 1\\
    0 \\
  \end{bmatrix}
  \hspace{35 em}
\end{equation}

</font>                 
</div>

<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 20px 5px 20px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.12 $\:\:$ Find the eigenvalues of

\begin{equation}
\textbf{A}\,=\,
  \begin{bmatrix}
    1 & 3 \\ 
    4 & 2 \\
  \end{bmatrix}
  \hspace{28 em}
\end{equation} 


     
     
     

</font> 
</div>

In [7]:
import numpy as np


a = np.array([[1, 3], [4, 2]])
a = np.array([[2*t, 5*t], [-1*t, -2*t]])
w, v = np.linalg.eig(a)

print(w)
print(v)



[-2.  5.]
[[-0.70710678 -0.6       ]
 [ 0.70710678 -0.8       ]]


<div style="background: #E2FFCC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 10px 5px 10px 5px; 
            border: 30px solid #E2FFCC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>Note the two variables w and v assigned to the output of numpy.linalg.eig(). The first variable w is assigned an array of computed eigenvalues and the second variable v is assigned the matrix whose columns are the normalized eigenvectors corresponding to the eigenvalues in that order. 

</font>                 
</div>

<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 20px 5px 20px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.13 $\:\:$ Find the eigenvalues of $\,\textbf{A}t\,$ if

\begin{equation}
\textbf{A}\,=\,
  \begin{bmatrix}
    2 & 5 \\ 
    -1 & -2 \\
  \end{bmatrix}
  \hspace{28 em}
\end{equation} 

     
     
     

</font> 
</div>

<div style="background: #E2FFCC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 10px 5px 10px 5px; 
            border: 30px solid #E2FFCC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>The eigenvalues can be found by Wolfram Alpha. If the entry is made:<br>
!| eigenvalues {{2 * t, 5 * t}, {-1 * t, -2 * t}} |!<br>

then the response is<br>

Results: $\,\lambda\,=\,it\,$ and $\,\lambda\,=\,-it\,$<br>
Corresponding eigenvectors: $\,v_1\,=\,(-2\,-\,i,\,1)\,$ and $\,(-2\,+\,i,\,1)\,$<br>

The $t$ factor in the problem expression makes getting an answer more difficult when Python is used than when W|A is used.

</font>                 
</div>

<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 60px 5px 60px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.14 $\:\:$ Find the eigenvalues of $\,\textbf{A}\,$ if

\begin{equation}
\textbf{A}\,=\,
  \begin{bmatrix}
    4 & 1 & 0 \\ 
    -1 & 2 & 0 \\
    2 & 1 & -3 \\
  \end{bmatrix}
  \hspace{28 em}
\end{equation} 
     
     
     

</font> 
</div>

<div style="background: #E2FFCC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 10px 5px 10px 5px; 
            border: 30px solid #E2FFCC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>The eigenvalues can be found by Wolfram Alpha. If the entry is made:<br>
!| eigenvalues {{4, 1, 0}, {-1, 2 , 0}, {2, 1, -3}} |!<br>

then the response is<br>

Results: $\,\lambda_1\,=\,-3\,$ and $\,\lambda_2\,=\,3\,$<br>
Corresponding eigenvectors: $\,v_1\,=\,(0,\,0,\,1)\,$ and $\,v_2\,=\,(6,\,-6,\,1)\,$<br>

</font>                 
</div>

<div style="background: #FFE3CC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 60px 5px 60px 5px; 
            border: 30px solid #FFE3CC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>15.15 $\:\:$ Find the eigenvalues of $\,\textbf{A}\,$ if

\begin{equation}
\textbf{A}\,=\,
  \begin{bmatrix}
    5 & 7 & 0 & 0 \\ 
    -3 & -5 & 0 & 0 \\
    0 & 0 & 2 & 1 \\
    0 & 0 & 0 & 2 \\
  \end{bmatrix}
  \hspace{28 em}
\end{equation} 
     
     
     

</font> 
</div>

<div style="background: #E2FFCC;
            font-family: Bookerly;
            font-size: 16px; 
            font-weight: 500;
            padding: 10px 5px 10px 5px; 
            border: 30px solid #E2FFCC; 
            margin-left: 1px;
            margin-right: 1px;"

<font color='blue'>The eigenvalues can be found by Wolfram Alpha. If the entry is made:<br>
!| eigenvalues {{5, 7, 0, 0}, {-3, 5, 0, 0}, {0, 0, 2, 1}, {0, 0, 0, 2}} |!<br>

then the response is<br>

Results: $\,\lambda_1\,=\,-2\,$ and $\,\lambda_2\,=\,2\,$ and $\,\lambda_3\,=\,2\,$<br>

Corresponding eigenvectors: $\,v_1\,=\,(-1,\, 1,\, 0,\, 0)\,$ and $\,v_2\,=\,(0,\, 0,\, 1,\, 0)\,$ and $\,v_3\,=\,(-7, \,3, \,0, \,0)\,$<br>

</font>                 
</div>